### ISSUE TITLE
Docker container 

### ISSUE THREAD

**Issue by aribornstein** [AlonEirew/wikipedia-to-elastic#2]
Docker image returns an empty 200 response when using the https://github.com/NervanaSystems/nlp-architect/blob/master/nlp_architect/data/cdc_resources/gen_scripts/create_wiki_dump.py script

**Comment by AlonEirew** [comment]
Hi Ari, 
I found an issue related to search, which only work for exact match and case-sensitive, which I'll fix and push new docker image.

Can you verify that this is the issue for you too by running this command for example:
`curl -XGET 'http://localhost:9200/enwiki_v2/_search?pretty=true' -H 'Content-Type: application/json' -d '
{
  "size": 5, "query": {
    "match_phrase": { "title.near_match": "Land"
    }
  }
}'`

**Comment by AlonEirew** [comment]
Issue fixed, new image pushed to docker hub
