### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by cooper12121** [AlonEirew/wikipedia-to-elastic#21]
![image](https://user-images.githubusercontent.com/55910045/229764202-7806a28d-ee15-4de5-9b15-ae21976e6dbc.png)
there has a problem when i run the command,the invalid or corrupt jar file,how can i solve this problem ,can you help me

**Comment by cooper12121** [comment]
![image](https://user-images.githubusercontent.com/55910045/229788365-8012e821-25f1-47de-86c8-b1d2a699c3b4.png)
can you tell how to solve this problem

**Comment by AlonEirew** [comment]
Hi @gaoqiang-3416, 

Regarding the configuration file, you need to set the attribute `wikidataDump` in `config/wikidata_conf.json` file, have you done that?
Regarding the corrupt jarfile, its the first time I'm encountering this issue, was this resolved?

**Comment by cooper12121** [comment]
> Hi @gaoqiang-3416,
> 
> Regarding the configuration file, you need to set the attribute `wikidataDump` in `config/wikidata_conf.json` file, have you done that? Regarding the corrupt jarfile, its the first time I'm encountering this issue, was this resolved?

i have resolve this problem,because i not not good at java,when i run the extract-wec project ,i meet another problem,can you help me,
![image](https://user-images.githubusercontent.com/55910045/229806611-c91c2ad8-d8bc-4f43-9203-09379a0482bc.png)

**Comment by cooper12121** [comment]
> Hi @gaoqiang-3416,
> 
> Regarding the configuration file, you need to set the attribute `wikidataDump` in `config/wikidata_conf.json` file, have you done that? Regarding the corrupt jarfile, its the first time I'm encountering this issue, was this resolved?

![image](https://user-images.githubusercontent.com/55910045/230045989-60667c53-659c-4769-9bd5-aff412a7ee8a.png)
![image](https://user-images.githubusercontent.com/55910045/230046133-354b67f3-2059-4fdc-bf8b-0aa4a7663532.png)
this problem happens again,i have set ther wikidata_conf.json,and in your code
![image](https://user-images.githubusercontent.com/55910045/230046445-42522a4c-8895-4c1b-bad0-bd5d6eeca5cc.png)
the mainConfiguration read the config.json,but it needs the data :  mainConfiguration.getWikidataDump(),mainConfiguration.getWikidataJsonOutput(),why it was set in wikidata_conf.json?

**Comment by AlonEirew** [comment]
Hi @gaoqiang-3416,
Sorry for the delay in responses. You are right, thank you for letting me know. 
I've just pushed a fix, pull it and let me know if now it is working. 
I'm closing this issue as it is the same as issue #22 and we'll continue there thread there on this issue.
