### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by cooper12121** [AlonEirew/wikipedia-to-elastic#22]
![image](https://user-images.githubusercontent.com/55910045/230330334-d5ebc34a-cbfb-466d-8ea2-615aa903df8c.png)
i have set the config/wi....json,but still have this problem,is the code right?
![image](https://user-images.githubusercontent.com/55910045/230330528-378ec876-f03f-47df-91d8-856cb23eb635.png)
because the mainconfiguation read the wikidumpfile,but its was set in config/wikidata_conf.json,maybe there exits a problem?
can you help me,thank you so much

**Comment by AlonEirew** [comment]
Hi @gaoqiang-3416, Thank you for noticing and reporting, I've just pushed a fix.
Let me know if fixed

**Comment by cooper12121** [comment]
> Hi @gaoqiang-3416, Thank you for noticing and reporting, I've just pushed a fix. Let me know if fixed

Thank you,i also have some problems,
![image](https://user-images.githubusercontent.com/55910045/230811459-033dda49-3904-4bce-8e70-6f15a0152fe2.png)
what is this json file used for,whether it is the wikidata,if it is ,is there a small version of it,it has 70G,it't too big
![image](https://user-images.githubusercontent.com/55910045/230811862-47475aee-a376-485f-a165-3f0bf31f6d87.png)
in your config,your wikidata is xml.bz2data,this is same to wikipedia data but not wikidata,

**Comment by AlonEirew** [comment]
The `Wikidata` dump file is used for generating additional information that only exist in [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page).
If your goal is to generate a [WEC](https://github.com/AlonEirew/extract-wec) dataset (as I understand), you don't need Wikidata, and you can ignore it.

For generating WEC, only the `Wikipedia` dump is required.
Hope this helps.
