### ISSUE TITLE
Elastic server storage space

### ISSUE THREAD

**Issue by markkuhar** [AlonEirew/wikipedia-to-elastic#23]
Hey @AlonEirew first of all, thanks for this!

Do you maybe know how much disk space on Elastic server does loading [enwiki-latest-pages-articles.xml.bz2](https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2) (currently at 19.5GB) takes?

**Comment by AlonEirew** [comment]
Hi @markkuhar, if you included the page text, I dont remember exactly but I think a bit less then 100G..
