### ISSUE TITLE
enwiki_mapping.json Missing

### ISSUE THREAD

**Issue by johnzupancic** [AlonEirew/wikipedia-to-elastic#9]
When you run the `build.sh` script in the Docker container, it can't find `enwiki_mapping.json` in the `elastic-dump` folder. I think you're missing it.

**Comment by AlonEirew** [comment]
Hi @johnzupancic, 
File should be part of the pulled docker image. 
Do you get any error message you can share?
Also will help if you remember on which step did it fail for you? (when running the steps in [https://github.com/AlonEirew/wikipedia-to-elastic#getting-the-index-with-docker](url))

Let know,
Thanks.
